In [1]:
import numpy as np

In [2]:
arr_1_d = np.asarray([1])
print(arr_1_d, arr_1_d.ndim, arr_1_d.shape)

[1] 1 (1,)


In [3]:
arr_2_d = np.asarray([[1, 2], [3, 4]])
print(arr_2_d, arr_2_d.ndim, arr_2_d.shape)

[[1 2]
 [3 4]] 2 (2, 2)


In [4]:
arr_2_d.reshape((4, 1))

array([[1],
       [2],
       [3],
       [4]])

In [5]:
arr_2_d.dtype

dtype('int64')

In [6]:
a = np.arange(6).reshape(2, 3, order="F")
a

array([[0, 2, 4],
       [1, 3, 5]])

In [7]:
arr_2_d.size

4

In [8]:
arr_2_d.dtype

dtype('int64')

## 创建数组的其他方式

创建数组的其他方式


In [9]:
np.ones((3, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [10]:
np.zeros((4, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [11]:
np.ones((2, 3)) * 0.78

array([[0.78, 0.78, 0.78],
       [0.78, 0.78, 0.78]])

In [12]:
np.arange(1, 46, 3)

array([ 1,  4,  7, 10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43])

In [13]:
np.linspace(3, 1024, 15)

array([   3.        ,   75.92857143,  148.85714286,  221.78571429,
        294.71428571,  367.64285714,  440.57142857,  513.5       ,
        586.42857143,  659.35714286,  732.28571429,  805.21428571,
        878.14285714,  951.07142857, 1024.        ])

## 数组中轴的概念

In [14]:
interest_score = np.random.randint(10, size=(4, 3))
interest_score

array([[9, 9, 7],
       [0, 1, 5],
       [7, 5, 5],
       [0, 6, 6]])

In [15]:
np.sum(interest_score, axis=0)

array([16, 21, 23])

In [16]:
np.sum(interest_score, axis=1)

array([25,  6, 17, 12])

In [20]:
from PIL import Image
im = Image.open('/Users/gege/workspace-code/2Learning/learning-python/assets/geektime-logo-wap.webp')
im.size

(700, 172)